<font color="green" size="5"><b>Data Cleaning</b></font>

In this step, the datasets are inspected and cleaned to ensure they are ready for analysis.  
The process includes handling missing values, removing duplicate records, validating data types, and performing basic quality checks.

<font color="green" size="4"><b>Importing necessary libraries</b></font>

In [ ]:
import pandas as pd
import numpy as np

<font color="green" size="4"><b>Loading the datasets</b></font>

In [ ]:
customers = pd.read_csv("../Data/customers.csv")
products = pd.read_csv("../Data/products.csv")
orders = pd.read_csv("../Data/orders.csv")
order_items = pd.read_csv("../Data/order_items.csv")
payments = pd.read_csv("../Data/payments.csv")

<font color="green" size="4"><b>Displaying the first few rows of each dataset</b></font>

In [ ]:
customers.head()

   customer_id country         segment signup_date
0            1   Spain  Small Business  2023-11-26
1            2   Italy        Consumer  2024-05-22
2            3  France        Consumer  2023-03-10
3            4   Spain  Small Business  2024-06-29
4            5   Spain        Consumer  2023-02-22

In [5]:
orders.head()

   order_id  customer_id  order_date     status
0         1            3  2024-05-10  Delivered
1         2          160  2024-12-18  Delivered
2         3          227  2024-07-14  Delivered
3         4          486  2024-10-07  Delivered
4         5          269  2024-06-02  Delivered

In [6]:
order_items.head()

   order_item_id  order_id  product_id  quantity
0              1       436          19         2
1              2       852          91         3
2              3       205          29         3
3              4      1100         100         2
4              5        77          35         4

In [4]:
products.head()

   product_id     category   price
0           1  Electronics  325.10
1           2         Home  348.12
2           3  Electronics   30.54
3           4       Sports  336.61
4           5         Home   26.86

In [7]:
payments.head()

   payment_id  order_id payment_method payment_status
0           1      1342  Bank Transfer        Success
1           2      1986  Bank Transfer        Success
2           3        14  Bank Transfer        Success
3           4       742  Bank Transfer        Success
4           5      1464  Bank Transfer        Success

<font color="green" size="4"><b>Checking the shape of the datasets</b></font>

In [ ]:
print("customers.shape:",customers.shape)
print("products.shape:", products.shape)
print("orders.shape:", orders.shape)
print("order_items.shape:", order_items.shape)
print("payments.shape:", payments.shape)

customers.shape: (500, 4)
products.shape: (100, 3)
orders.shape: (2050, 4)
order_items.shape: (5000, 4)
payments.shape: (2000, 4)

In [ ]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  500 non-null    int64
 1   country      480 non-null    str
 2   segment      500 non-null    str
 3   signup_date  500 non-null    str
dtypes: int64(1), str(3)
memory usage: 15.8 KB

In [15]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   product_id  100 non-null    int64
 1   category    100 non-null    str
 2   price       100 non-null    float64
dtypes: float64(1), int64(1), str(1)
memory usage: 2.5 KB

In [16]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 2050 entries, 0 to 2049
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     2050 non-null   int64
 1   customer_id  2050 non-null   int64
 2   order_date   2050 non-null   str
 3   status       2050 non-null   str
dtypes: int64(2), str(2)
memory usage: 64.2 KB

In [17]:
order_items.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_item_id  5000 non-null   int64
 1   order_id       5000 non-null   int64
 2   product_id     5000 non-null   int64
 3   quantity       5000 non-null   int64
dtypes: int64(4)
memory usage: 156.4 KB

In [18]:
payments.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   payment_id      2000 non-null   int64
 1   order_id        2000 non-null   int64
 2   payment_method  2000 non-null   str
 3   payment_status  2000 non-null   str
dtypes: int64(2), str(2)
memory usage: 62.6 KB

<font color="green" size="4"><b>Checking for missing values in the datasets & handling Missing Values</b></font>

In [ ]:
customers.isnull().sum()

customer_id     0
country        20
segment         0
signup_date     0
dtype: int64

In [20]:
products.isnull().sum()

product_id    0
category      0
price         0
dtype: int64

In [21]:
orders.isnull().sum()

order_id       0
customer_id    0
order_date     0
status         0
dtype: int64

In [22]:
order_items.isnull().sum()

order_item_id    0
order_id         0
product_id       0
quantity         0
dtype: int64

In [23]:
payments.isnull().sum()

payment_id        0
order_id          0
payment_method    0
payment_status    0
dtype: int64

<font color="green" size="4"><b>Checking the rows with missing values in the customers dataset</b></font>

In [ ]:
customers[customers["country"].isnull()]

     customer_id country         segment signup_date
45            46     NaN  Small Business  2023-08-02
63            64     NaN        Consumer  2024-04-18
97            98     NaN        Consumer  2024-01-29
121          122     NaN        Consumer  2024-03-12
129          130     NaN       Corporate  2024-03-21
167          168     NaN  Small Business  2023-03-31
172          173     NaN        Consumer  2024-05-25
189          190     NaN       Corporate  2024-02-23
218          219     NaN  Small Business  2023-03-30
236          237     NaN  Small Business  2023-02-08
267          268     NaN  Small Business  2023-08-04
308          309     NaN  Small Business  2024-01-13
309          310     NaN        Consumer  2023-02-20
362          363     NaN       Corporate  2024-11-19
393          394     NaN  Small Business  2023-08-10
400          401     NaN  Small Business  2023-06-11
409          410     NaN        Consumer  2023-11-09
454          455     NaN  Small Business  2023-02-22
468          469     NaN        Consumer  2024-07-05
475          476     NaN       Corporate  2024-05-08

<font color="green" size="4"><b>Filling the missing values in the country column with "Unknown" to preserve customer records</b></font>

In [ ]:
customers["country"] = customers["country"].fillna("Unknown")
customers.isnull().sum()

customer_id    0
country        0
segment        0
signup_date    0
dtype: int64

<font color="green" size="4"><b>Checking for duplicate rows in the datasets</b></font>

In [28]:
customers.duplicated().sum()

np.int64(0)

In [30]:
payments.duplicated().sum()

np.int64(0)

In [31]:
order_items.duplicated().sum()

np.int64(0)

In [32]:
products.duplicated().sum()

np.int64(0)

In [29]:
orders.duplicated().sum()

np.int64(50)

<font color="green" size="4"><b>Removing Duplicates from Orders Dataset</b></font>

In [36]:
orders = orders.drop_duplicates()
orders.duplicated().sum()

np.int64(0)

<font color="green" size="4"><b>Validating Data Types</b></font>

In [37]:
orders.dtypes

order_id       int64
customer_id    int64
order_date       str
status           str
dtype: object

In [38]:
customers.dtypes

customer_id    int64
country          str
segment          str
signup_date      str
dtype: object

In [39]:
orders["order_date"] = pd.to_datetime(orders["order_date"])
customers["signup_date"] = pd.to_datetime(customers["signup_date"])

In [41]:
orders.dtypes

order_id                int64
customer_id             int64
order_date     datetime64[us]
status                    str
dtype: object

In [40]:
customers.dtypes

customer_id             int64
country                   str
segment                   str
signup_date    datetime64[us]
dtype: object

<font color="green" size="4"><b>Validating Unique Values</b></font>

In [42]:
orders["status"].value_counts()

status
Delivered    1610
Cancelled     199
Returned      191
Name: count, dtype: int64

In [43]:
payments["payment_status"].value_counts()

payment_status
Success    1791
Failed      209
Name: count, dtype: int64

In [44]:
payments["payment_method"].value_counts()

payment_method
Bank Transfer    727
Card             638
PayPal           635
Name: count, dtype: int64

<font color="green" size="4"><b>Save Clean Data</b></font>

In [45]:
customers.to_csv("../Data/customers_clean.csv", index=False)
orders.to_csv("../Data/orders_clean.csv", index=False)