<font color="green" size="5"><b>Data Modeling</b></font>

In this step, the different datasets are joined to create a final analytical table.
This table will be used for analysis, KPI calculations, and dashboard creation.

The following tables are joined:
- customers
- orders
- order_items
- products
- payments

<font color="green" size="4"><b>Importing necessary libraries</b></font>

In [1]:
import pandas as pd
import numpy as np

<font color="green" size="4"><b>Loading the datasets</b></font>

In [2]:
customers = pd.read_csv("../Data/customers_clean.csv")
products = pd.read_csv("../Data/products.csv")
orders = pd.read_csv("../Data/orders_clean.csv")
order_items = pd.read_csv("../Data/order_items.csv")
payments = pd.read_csv("../Data/payments.csv")

<font color="green" size="4"><b>Validating Relationships (orders ↔ customers)
(order_items ↔ products)
</b></font>

In [ ]:
# Validate that all customer_ids in orders exist in customers (check orders → customers relationship)
# This ensures that every order is associated with a valid customer.
orders["customer_id"].isin(customers["customer_id"]).all()

np.True_

In [ ]:
# Validate that all product_ids in order_items exist in products (check order_items → products relationship)
# This ensures that every order item references a valid product.

order_items["product_id"].isin(products["product_id"]).all()

np.True_

<font color="green" size="4"><b>Joining tables to create a final analytical table</b></font>

In [ ]:
# Join Orders + Customers

df = orders.merge(customers, on="customer_id", how="left")

In [ ]:
# Join Order Items

df = df.merge(order_items, on="order_id", how="left")

In [ ]:
# Join Products

df = df.merge(products, on="product_id", how="left")

In [ ]:
# Join Payments

df = df.merge(payments, on="order_id", how="left")

<font color="green" size="4"><b>Creating Revenue Column</b></font>

In [9]:
df["revenue"] = df["quantity"] * df["price"]

<font color="green" size="4"><b>Creating Valid Order</b></font>

In [10]:
df["valid_order"] = (
    (df["status"] == "Delivered") &
    (df["payment_status"] == "Success")
)

In [ ]:
# Display the first few rows of the final DataFrame

df.head()

,order_id,customer_id,order_date,status,country,segment,signup_date,order_item_id,product_id,quantity,category,price,payment_id,payment_method,payment_status,revenue,valid_order
0,1,3,2024-05-10,Delivered,France,Consumer,2023-03-10,951.0,79.0,1.0,Electronics,372.96,177.0,Bank Transfer,Success,372.96,True
1,1,3,2024-05-10,Delivered,France,Consumer,2023-03-10,2961.0,62.0,4.0,Electronics,359.20,177.0,Bank Transfer,Success,1436.80,True
2,1,3,2024-05-10,Delivered,France,Consumer,2023-03-10,4584.0,10.0,3.0,Sports,159.86,177.0,Bank Transfer,Success,479.58,True
3,2,160,2024-12-18,Delivered,Italy,Corporate,2024-02-14,NaN,NaN,NaN,NaN,NaN,1543.0,Bank Transfer,Success,NaN,True
4,3,227,2024-07-14,Delivered,France,Consumer,2024-02-26,103.0,20.0,4.0,Clothing,263.61,725.0,PayPal,Success,1054.44,True

In [15]:
df.shape

(5393, 17)

In [23]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5393 entries, 0 to 5392
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        5393 non-null   int64
 1   customer_id     5393 non-null   int64
 2   order_date      5393 non-null   str
 3   status          5393 non-null   str
 4   country         5393 non-null   str
 5   segment         5393 non-null   str
 6   signup_date     5393 non-null   str
 7   order_item_id   5226 non-null   float64
 8   product_id      5226 non-null   float64
 9   quantity        5226 non-null   float64
 10  category        5226 non-null   str
 11  price           5226 non-null   float64
 12  payment_id      5278 non-null   float64
 13  payment_method  5278 non-null   str
 14  payment_status  5278 non-null   str
 15  revenue         5226 non-null   float64
 16  valid_order     5393 non-null   bool
dtypes: bool(1), float64(6), int64(2), str(8)
memory usage: 679.5 KB

In [18]:
df.describe()

,order_id,customer_id,order_item_id,product_id,quantity,price,payment_id,revenue
count,5393.000000,5393.000000,5226.000000,5226.000000,5226.000000,5226.000000,5278.000000,5226.000000
mean,1020.666605,249.896718,2499.188289,50.354573,2.506123,248.081808,1006.668814,624.610356
std,577.495162,145.831928,1443.430447,28.732397,1.108325,145.664673,581.641757,488.466935
min,1.000000,1.000000,1.000000,1.000000,1.000000,5.120000,1.000000,5.120000
25%,532.000000,123.000000,1247.250000,25.000000,2.000000,133.200000,498.250000,230.300000
50%,1041.000000,253.000000,2497.500000,51.000000,2.000000,260.050000,1017.500000,499.680000
75%,1518.000000,379.000000,3748.750000,75.000000,3.000000,367.470000,1510.750000,921.200000
max,2000.000000,500.000000,5000.000000,100.000000,4.000000,499.680000,2000.000000,1998.720000

In [20]:
df["valid_order"].value_counts()

valid_order
True     3789
False    1604
Name: count, dtype: int64

In [21]:
df["revenue"].sum()

np.float64(3264213.7199999997)

In [22]:
df["status"].value_counts()

status
Delivered    4310
Returned      572
Cancelled     511
Name: count, dtype: int64

<font color="green" size="4"><b>Saving Final Dataset</b></font>

In [19]:
df.to_csv("../Data/Final_Dataset.csv", index=False)